/// Flutter icons Aum
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Aum
///      fonts:
///       - asset: fonts/Aum.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Aum {
  Aum._();

  static const _kFontFam = 'Aum';
  static const _kFontPkg = null;

  static const IconData astrology = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aum_learning = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_dates = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_nofill = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hindu_temple = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData man = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificationschool_bell = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData om_no_circle = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData poojari = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_bag = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart_new = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_filled = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sunrise = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sunset = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData support = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_camera = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_player = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData woman = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zodiac_aquarius = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zodiac_aries = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zodiac_cancer = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zodiac_capricorn = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zodiac_gemini = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zodiac_leo = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zodiac_libra = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zodiac_pisces = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zodiac_sagittarius = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zodiac_scorpio = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zodiac_taurus = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zodiac_virgo = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_circle = IconData(0xf2bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
